from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.book import Book
from openapi_server import util

from openapi_server.models.book import Book  # noqa: E501

class GetUsersBooks200ResponseInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, book=None, pages_read=None):  # noqa: E501
        """GetUsersBooks200ResponseInner - a model defined in OpenAPI

        :param book: The book of this GetUsersBooks200ResponseInner.  # noqa: E501
        :type book: Book
        :param pages_read: The pages_read of this GetUsersBooks200ResponseInner.  # noqa: E501
        :type pages_read: int
        """
        self.openapi_types = {
            'book': Book,
            'pages_read': int
        }

        self.attribute_map = {
            'book': 'book',
            'pages_read': 'pagesRead'
        }

        self._book = book
        self._pages_read = pages_read

    @classmethod
    def from_dict(cls, dikt) -> 'GetUsersBooks200ResponseInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The get_users_books_200_response_inner of this GetUsersBooks200ResponseInner.  # noqa: E501
        :rtype: GetUsersBooks200ResponseInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def book(self) -> Book:
        """Gets the book of this GetUsersBooks200ResponseInner.


        :return: The book of this GetUsersBooks200ResponseInner.
        :rtype: Book
        """
        return self._book

    @book.setter
    def book(self, book: Book):
        """Sets the book of this GetUsersBooks200ResponseInner.


        :param book: The book of this GetUsersBooks200ResponseInner.
        :type book: Book
        """

        self._book = book

    @property
    def pages_read(self) -> int:
        """Gets the pages_read of this GetUsersBooks200ResponseInner.


        :return: The pages_read of this GetUsersBooks200ResponseInner.
        :rtype: int
        """
        return self._pages_read

    @pages_read.setter
    def pages_read(self, pages_read: int):
        """Sets the pages_read of this GetUsersBooks200ResponseInner.


        :param pages_read: The pages_read of this GetUsersBooks200ResponseInner.
        :type pages_read: int
        """

        self._pages_read = pages_read
