name: Test project
on: [workflow_dispatch, push]
jobs: 
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            # - name: Set up python version
            #   uses: actions/setup-python@v5
            #   with: 
            #     python-version: '3.12'
            
            - name: Print hello
              run: echo "Hello"
            
                    




        
